# Generated by Django 5.0 on 2023-12-28 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=100000)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('room', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20)),
                ('admin', models.CharField(max_length=20)),
                ('roomID', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(default=0, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=10)),
                ('joined', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 28, 18, 51, 4, 188499))),
            ],
        ),
    ]
