# Generated by Django 5.0 on 2023-12-28 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 28, 18, 59, 7, 702235)),
        ),
    ]
